### ISSUE TITLE
Add response pipe option for extra sanity checks

### ISSUE THREAD

**Issue by sebasslash** [Serdnad/yester#3]
There are instances I'd like to inspect the response body. Moreover, I would like to be able to specify the destination this response body will be piped to, albeit `stdout` or some file `inspect.txt`. 

```yaml
exampleTest:
  request: 
    path: /example/resource,
    method: GET
  validation:
    statuscode: 200
    pipeResponse: stdout
    body:
    - body[0].id == "foo"
    - something else here
```
Thanks.
