### ISSUE TITLE
Environment Variable Support

### ISSUE THREAD

**Issue by sebasslash** [Serdnad/yester#4]
I would like the option to read in env variables, especially useful for defaults:

```yaml
base: env.BASE_URL
defaults:
  auth_token: env.AUTH_TOKEN
  ...
```
